"""Regenerate final synthetic diagnostics and the anonymous vector fan figure.

Use the pinned Python requirements. The default run also needs pdflatex and
the standalone/TikZ packages; --skip-figure runs the Python diagnostics alone.
Numerical diagnostics are delegated unchanged to context_games.qq_audit.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from context_games.qq_audit import generate, running_example_rows


def running_table() -> str:
    """Present the unchanged running-example calculations without legacy names."""
    sign = {-1: "-", 0: "0", 1: "+"}
    body = [
        rf"\(({row['x1']},{row['x2']})\) & "
        rf"\(({row['e1']:g},{row['e2']:g})\) & "
        rf"\(({sign[row['s1']]},{sign[row['s2']]})\)"
        for row in running_example_rows()
    ]
    return (
        "% Generated by scripts/run_qq_final_audit.py; do not edit by hand.\n"
        "\\begin{table}[tbp]\n\\centering\n\\small\n"
        "\\setlength{\\tabcolsep}{4pt}\n\\begin{tabular}{ccc}\n\\toprule\n"
        "Outcome \\(x\\) & \\(E_C(x)\\) & Signature\\\\\n\\midrule\n"
        + "\\\\\n".join(body)
        + "\\\\\n\\bottomrule\n\\end{tabular}\n"
        "\\caption{Recomputed running-example outcomes. Signatures label evaluated "
        "outcomes relative to the declared context, not types of people.}\n"
        "\\label{tab:running-labels}\n\\end{table}\n"
    )


def compile_figure(output: Path) -> None:
    """Compile the fixed scientific geometry; keep auxiliary files temporary."""
    executable = shutil.which("pdflatex")
    if executable is None:
        raise RuntimeError("pdflatex is required for the figure; use --skip-figure for diagnostics only")
    source = ROOT / "figures/contextual_fans_final.tex"
    environment = dict(os.environ, SOURCE_DATE_EPOCH="0", FORCE_SOURCE_DATE="1")
    with tempfile.TemporaryDirectory(prefix="qq-final-figure-") as temporary:
        directory = Path(temporary)
        shutil.copyfile(source, directory / source.name)
        completed = subprocess.run(
            [executable, "-interaction=nonstopmode", "-halt-on-error", source.name],
            cwd=directory, env=environment, capture_output=True, text=True,
        )
        if completed.returncode:
            raise RuntimeError("Figure compilation failed:\n" + completed.stdout[-8000:])
        shutil.copyfile(directory / "contextual_fans_final.pdf",
                        output / "figure_contextual_fans_final.pdf")


def refresh_provenance(provenance: dict, output: Path, *, figure_compiled: bool) -> dict:
    """Retain the diagnostic record, then hash the actual final presentation."""
    result = dict(provenance)
    result["source_sha256"] = dict(provenance["source_sha256"])
    for relative in (
        "scripts/run_qq_final_audit.py",
        "figures/contextual_fans_final.tex",
        "tests/test_qq_final_presentation.py",
    ):
        result["source_sha256"][relative] = hashlib.sha256((ROOT / relative).read_bytes()).hexdigest()
    result["outputs_sha256"] = {
        path.name: hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(output.iterdir())
        if path.is_file() and path.name != "provenance.json"
    }
    result["reproduction_command"] = "python scripts/run_qq_final_audit.py --output-dir results/qq_final"
    if not figure_compiled:
        result["reproduction_command"] += " --skip-figure"
    result["final_presentation"] = {
        "numerical_diagnostics": "Unchanged from context_games.qq_audit.generate",
        "running_table": "Three columns: outcome, evaluation, signature; no legacy class names",
        "figure_compiled": figure_compiled,
        "figure_dependency": "pdflatex with standalone and TikZ; only needed when compiling the figure",
        "figure_geometry": "Original axes, normal lines, reference and label coordinates preserved",
    }
    return result


def generate_final(output: Path, *, with_figure: bool = True) -> dict:
    provenance = generate(output)
    (output / "table_running_labels.tex").write_text(running_table(), encoding="utf-8")
    if with_figure:
        compile_figure(output)
    provenance = refresh_provenance(provenance, output, figure_compiled=with_figure)
    (output / "provenance.json").write_text(json.dumps(provenance, indent=2) + "\n", encoding="utf-8")
    return provenance


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("results/qq_final"))
    parser.add_argument("--skip-figure", action="store_true",
                        help="generate diagnostics without invoking LaTeX")
    args = parser.parse_args()
    provenance = generate_final(args.output_dir, with_figure=not args.skip_figure)
    print(f"Generated {len(provenance['outputs_sha256'])} final audit artifacts in {args.output_dir}")


if __name__ == "__main__":
    main()
